### ISSUE TITLE
Use default UUID generators from Laravel version

### ISSUE THREAD

**Issue by yespbs** [jamesmills/eloquent-uuid#19]
Lets use default version of uuid generation from laravel, Laravel 7 clashes with ramsey/uuid

**Comment by jamesmills** [comment]
Great idea, PR welcome. Thanks.

**Comment by yespbs** [comment]
Will do some time next week. It will just remove dependency of ramsey/uuid and use default version that comes with Laravel, will test laravel 5.8+ not below
