### ISSUE TITLE
Error on compose install

### ISSUE THREAD

**Issue by renanwilliam** [jamesmills/eloquent-uuid#22]
When I try to install using composer, this error is throwing:
`Could not load package jamesmills/eloquent-uuid in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^5.2.*: Invalid version string "^5.2.*"`

![image](https://user-images.githubusercontent.com/19995615/93524405-d498e300-f90a-11ea-8af0-76c1d7b6a8a2.png)

**Comment by 1070rik** [comment]
Running `composer self-update` and trying again worked for me :)

**Comment by jamesmills** [comment]
Don't think we supported 5.2.*. Luckily for you @djoudi added a PR to add this. Try again now.

**Comment by renanwilliam** [comment]
Erasing vendor folder, `composer self-update` and `composer install` again solved the issue
