### ISSUE TITLE
Proposal: Performance issue with Schema::hasColumn($model->getTable(), 'uuid')

### ISSUE THREAD

**Issue by patriziotomato** [jamesmills/eloquent-uuid#4]
Is it really necessary to have this check as it sends an additional DB request while the developer has to decide on which model to include this trait or not. Means: The developer already checks if the column exists, so let's get rid of the additional database query.

**Comment by jamesmills** [comment]
Hi @patriziotomato and thanks for your feedback. 

Interesting idea. I think it is safe to assume that the developer has made sure that the UUID column is on the table for which the trait has been added. However, I am never a fan of assumptions.

Let me give this some thought.

**Comment by patriziotomato** [comment]
One idea is to handle it in your ServiceProvider's boot method. There you can iterate throw all classes implementing your trait and do this check. This way you're checking at least only at "boot-time", not with each query. For our case, we could not use your package, as it doubles all sql requests with uuid-tables which is a serious performance issue. So let's think of moving this check to boot()-time. Even better compile-time, which of course is not possible in PHP ;-)

**Comment by jamesmills** [comment]
It's an interesting one. I added the check at first to try and make the package helpful to the developer if they had added the Trait and added the migration but had forgotten to actually run the migration (it happens to the best of us). 

It was just an elegant way of saying "Hey, you forgot to add the UUID column". However, if you add the Trait and then don't run the migration to add the UUID then it's going to throw an error which you would be able to understand and fix anyway.

So maybe both are the say but one way causes a performance issue and I should just remove it.

**Comment by patriziotomato** [comment]
totally agree with that
