### ISSUE TITLE
Route Model Binding for UUID

### ISSUE THREAD

**Issue by jamesmills** [jamesmills/eloquent-uuid#6]
Another cool thing would be default key be set to Model binding...

I already have a trait to create my Uuids, but if your package had this option I would use it for sure!

My trait:

```
<?php

namespace App\Traits;

use Str;

trait Uuid
{
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function bootUuid()
    {
        static::creating(function ($model) {
            $model->uuid = Str::uuid();
        });
    }
}
```

_Originally posted by @caiokawasaki in https://github.com/jamesmills/eloquent-uuid/issues/3#issuecomment-518057595_

**Comment by jamesmills** [comment]
@caiokawasaki I have split this out into a new issue. I like this idea and I would love to add something which would enable wider use of the package.

Would we just need to add the 

```
public function getRouteKeyName()
    {
        return 'uuid';
    }
```

To the trait in the package?

**Comment by caiokawasaki** [comment]
@jamesmills yes! It's called Implicit Binding: https://laravel.com/docs/5.8/routing#implicit-binding

**Comment by jamesmills** [comment]
Fancy submitting a PR :-)

**Comment by yespbs** [comment]
I have quite some time using almost similar trait but since you have packaged it, its best to use yours :)

it just misses yes the implicit binding 

just adding 

/**
	 * Get the route key for the model.
	 *
	 * @return string
	 */
	public function getRouteKeyName()
	{
	    return 'uuid';
	}

will do

**Comment by jamesmills** [comment]
Thank you @yespbs 

This was PR and submitted in #7

**Comment by jamesmills** [comment]
If you fancy updating the README with examples too that would be amazing! Thanks for your support and contribution.

**Comment by yespbs** [comment]
added notes, since its resource controller related, added example with that.
